### ISSUE TITLE
DuplicateKey error in curator tag

### ISSUE THREAD

**Issue by alanorth** [AlexAltea/curator#11] opened 2023-02-18 17:08 UTC
I was testing the new rich text UI with curator tag and I get a crash:

```console
$ chrt -b 0 curator tag -s audio -t language --only-macrolanguages --log=DEBUG --max-audio-samples=10 06x01.mkv
2023-02-18 20:04:21,296 | INFO | Analyzing 1 input media files
2023-02-18 20:04:21,452 | DEBUG | Detecting audio language in stream #1 of media: "06x01.mkv"
2023-02-18 20:04:24,146 | DEBUG | Sample #00: {'en': '0.9950', 'fr': '0.0009', 'ja': '0.0006', 'pt': '0.0006', 'es': '0.0004'}
2023-02-18 20:04:25,447 | DEBUG | Sample #01: {'en': '0.9824', 'ms': '0.0054', 'zh': '0.0020', 'nn': '0.0017', 'es': '0.0009'}
2023-02-18 20:04:26,821 | DEBUG | Sample #02: {'en': '0.9983', 'pt': '0.0004', 'es': '0.0002', 'ja': '0.0002', 'la': '0.0001'}
2023-02-18 20:04:28,171 | DEBUG | Sample #03: {'en': '0.9987', 'nn': '0.0002', 'ms': '0.0002', 'ja': '0.0002', 'es': '0.0001'}
2023-02-18 20:04:29,566 | DEBUG | Sample #04: {'en': '0.9974', 'ms': '0.0007', 'nn': '0.0004', 'cy': '0.0002', 'zh': '0.0002'}
2023-02-18 20:04:31,034 | DEBUG | Sample #05: {'en': '0.9988', 'ja': '0.0003', 'es': '0.0001', 'nn': '0.0001', 'ms': '0.0001'}
2023-02-18 20:04:32,437 | DEBUG | Sample #06: {'en': '0.9959', 'ja': '0.0012', 'pt': '0.0005', 'ko': '0.0003', 'es': '0.0002'}
2023-02-18 20:04:33,905 | DEBUG | Sample #07: {'en': '0.9982', 'nn': '0.0002', 'ms': '0.0002', 'pt': '0.0002', 'ja': '0.0001'}
2023-02-18 20:04:35,380 | DEBUG | Sample #08: {'en': '0.9666', 'ko': '0.0050', 'zh': '0.0042', 'ja': '0.0030', 'de': '0.0025'}
2023-02-18 20:04:36,763 | DEBUG | Sample #09: {'en': '0.9799', 'zh': '0.0028', 'es': '0.0022', 'nn': '0.0018', 'ja': '0.0018'}
2023-02-18 20:04:36,769 | DEBUG | Using selector: EpollSelector
╭────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────╮
│ /home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/tui.py:83 in on_mount                                                       │
│                                                                                                                                                       │
│    80 │   │   # Add table contents                                                                                                                    │
│    81 │   │   table = self.query_one(DataTable)                                                                                                       │
│    82 │   │   for column in self.get_columns():                                                                                                       │
│ ❱  83 │   │   │   table.add_column(column['name'])                                                                                                    │
│    84 │   │   for task in self.plan:                                                                                                                  │
│    85 │   │   │   for row in task.view():                                                                                                             │
│    86 │   │   │   │   row = [Text(str(task.id), justify="right", overflow='ellipsis')] + \                                                            │
│                                                                                                                                                       │
│ ╭────────────────────────── locals ───────────────────────────╮                                                                                       │
│ │ column = {'name': 'New', 'width': '25%'}                    │                                                                                       │
│ │   self = EditorApp(title='Curator', classes={'-dark-mode'}) │                                                                                       │
│ │  table = TaskFlow()                                         │                                                                                       │
│ ╰─────────────────────────────────────────────────────────────╯                                                                                       │
│                                                                                                                                                       │
│ /home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/tui.py:48 in add_column                                                     │
│                                                                                                                                                       │
│    45 │   def add_column(self, name):                                                          ╭──────── locals ─────────╮                            │
│    46 │   │   align = "right" if name == "#" else None                                         │ align = None            │                            │
│    47 │   │   label = Text(name, overflow='ellipsis', justify=align)                           │ label = <text 'New' []> │                            │
│ ❱  48 │   │   super().add_column(label, key=name)                                              │  name = 'New'           │                            │
│    49 │                                                                                        │  self = TaskFlow()      │                            │
│    50 │   # HACK: Overriding private method                                                    ╰─────────────────────────╯                            │
│    51 │   def _render_line_in_row(self, row_key, line_no, base_style, cursor_location, hover_l                                                        │
│                                                                                                                                                       │
│ /home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/textual/widgets/_data_table.py:1042 in add_column                                   │
│                                                                                                                                                       │
│   1039 │   │   """                                                                              ╭────────────── locals ───────────────╮               │
│   1040 │   │   column_key = ColumnKey(key)                                                      │ column_key = ColumnKey(value='New') │               │
│   1041 │   │   if column_key in self._column_locations:                                         │        key = 'New'                  │               │
│ ❱ 1042 │   │   │   raise DuplicateKey(f"The column key {key!r} already exists.")                │      label = <text 'New' []>        │               │
│   1043 │   │   column_index = len(self.columns)                                                 │       self = TaskFlow()             │               │
│   1044 │   │   label = Text.from_markup(label) if isinstance(label, str) else label             │      width = None                   │               │
│   1045 │   │   content_width = measure(self.app.console, label, 1)                              ╰─────────────────────────────────────╯               │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
DuplicateKey: The column key 'New' already exists.
After changes, the current plan has 1 tasks enabled out of 1.
Apply plan? [y/N]
```

Here's the stream dump from the media file:

```json
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 1280,
            "height": 720,
            "coded_width": 1280,
            "coded_height": 720,
            "closed_captions": 0,
            "film_grain": 0,
            "has_b_frames": 2,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 41,
            "chroma_location": "left",
            "field_order": "progressive",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "24000/1001",
            "avg_frame_rate": "24000/1001",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "bits_per_raw_sample": "8",
            "extradata_size": 40,
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "eng"
            }
        },
        {
            "index": 1,
            "codec_name": "ac3",
            "codec_long_name": "ATSC A/52A (AC-3)",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "initial_padding": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "bit_rate": "384000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            }
        }
    ]
}
```

**Comment by AlexAltea** [comment] 2023-02-21 21:58
Sorry for the late reply, intense week IRL.

Found the root cause, just a silly typo when porting the code to the new system.

Fixed in https://github.com/AlexAltea/curator/commit/031d112a06a265a4072d6976d1d7063702386438.

**Closed as completed by AlexAltea** 2023-02-21 21:58 UTC

**Comment by alanorth** [comment] 2023-02-22 05:35
> Sorry for the late reply, intense week IRL.

No problem, I know the feeling.

Yes it's fixed now. Wow that's a fancy text UI!
